pipeline {
    agent any

  stages {
    stage('Build') {
      steps {
        script {
          sh 'echo "Building Stage"'
        }
      }
    }

    stage('Test') {
      steps {
        script {
          sh 'echo "Testing Stage"'
        }
      }
    }

    stage('package') {
      steps {
        script {
          sh 'echo "Packaging Stage"'
        }
      }
    }

    stage('deploy') {
      steps {
        script {
          sh 'echo "Deploying Stage"'
        }
      }
    }

    stage('clean up') {
      steps {
        script {
          sh 'echo "clean up Stage"'
        }
      }
    }
    }
}

