---
# - name: Include dynamic variables
#   hosts: wbsrvrs
#   tasks:
# - import_playbook: ../static-assignments/common.yml 
#   include: ../dynamic-assignments/env-vars.yml
#   tags:
#     - always
# - name: webserver configurations
#   hosts: wbsrvrs
# - name: Webserver assignment
#   import_playbook: ../static-assignments/webservers.yml

# - name: Loadbalancers assignment
#   hosts: lb
# - import_playbook: ../static-assignments/loadbalancers.yml
#   when: load_balancer_is_required 

- name: installing nginx
  hosts: nginx
- name: nginx assignment
  import_playbook: ../static-assignments/webservers.yml
