---
- name: Install Java 11
  yum:
   name: java-11-openjdk-devel
   state: present

- name: Download/fetch the repo from the internet
  get_url:
   url: https://release.jfrog.io/artifactory/artifactory-rpms/artifactory-rpms.repo
   dest: /home/ec2-user/jfrog-artifactory-rpms.repo
   mode: '0755'

- name: Copy the downloaded file into the etc repo
  copy:
   src: /home/ec2-user/jfrog-artifactory-rpms.repo
   dest: /etc/yum.repos.d/
   remote_src: yes
   follow: yes

- name: Updating cache
  yum:
   update_cache: yes  

- name: Install Artifactory
  yum:
   name: jfrog-artifactory-oss
   state: present

- name: Start Artifactory
  service:
   name: artifactory
   state: started
   enable: yes
